docker/main/diary/config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'
  get 'login', to: 'login#index'
  post 'login', to: 'login#do_login'
  post 'logout', to: 'logout#index'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

docker/main/diary/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

docker/main/diary/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

docker/main/diary/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

docker/main/diary/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_user
  private
  def load_user
    @current_user = nil
    if session[:user_id]
      begin
        @current_user = User.find(session[:user_id])
      rescue
      end
    end
  end
end

docker/main/diary/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :need_login, except: [:index, :show]
  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end
  def create
    @article = Article.new
    @article.user = @current_user
    @article.title = params[:article][:title]
    @article.content = params[:article][:content]
    @article.save!
    redirect_to article_url(@article.id)
  end
  def show
    begin
      @article = Article.find(params[:id])
    rescue
      redirect_to action: 'index'
      return
    end
  end
  def edit
    begin
      @article = Article.find(params[:id])
    rescue
      redirect_to action: 'index'
      return
    end
    unless @article.user_id == @current_user.id
      redirect_to action: 'show', id: @article.id
      return
    end
  end
  def update
    begin
      @article = Article.find(params[:id])
    rescue
      redirect_to action: 'index'
      return
    end
    unless @article.user_id == @current_user.id
      redirect_to action: 'show', id: @article.id
      return
    end
    @article.title = params[:article][:title]
    @article.content = params[:article][:content]
    @article.save!
    redirect_to article_url(@article.id)
  end
  def destroy
    begin
      @article = Article.find(params[:id])
    rescue
      redirect_to action: 'index'
      return
    end
    unless @article.user_id == @current_user.id
      redirect_to action: 'show', id: @article.id
      return
    end
    @article.destroy!
    redirect_to action: 'index'
  end
  private
  def need_login
    redirect_to action: 'index' unless @current_user
  end
end

docker/main/diary/app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :need_not_login
  def index
  end
  def do_login
    user = User.find_by name: params[:username]
    unless user
      redirect_to action: 'index'
      return
    end
    unless user.authenticate(params[:password])
      redirect_to action: 'index'
      return
    end
    session[:user_id] = user.id
    redirect_to controller: 'top', action: 'index'
  end
  private
  def need_not_login
    redirect_to controller: 'top',
      action: 'index' if @current_user
  end
end

docker/main/diary/app/controllers/logout_controller.rb
class LogoutController < ApplicationController
  before_action :need_login
  def index
    session.delete(:user_id)
    redirect_to controller: 'top', action: 'index'
  end
  private
  def need_login
    redirect_to controller: 'top',
      action: 'index' unless @current_user
  end
end

docker/main/diary/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

docker/main/diary/app/helpers/application_helper.rb
module ApplicationHelper
end

docker/main/diary/app/helpers/articles_helper.rb
module ArticlesHelper
end

docker/main/diary/app/helpers/login_helper.rb
module LoginHelper
end

docker/main/diary/app/helpers/logout_helper.rb
module LogoutHelper
end

docker/main/diary/app/helpers/top_helper.rb
module TopHelper
end

docker/main/diary/app/views/articles/edit.html.erb
<h1>記事編集</h1>
<%= form_with model: @article do |form| %>
<p><label>タイトル<%= form.text_field :title %></label></p>
<p><label>本文<br />
<%= form.text_area :content %></label></p>
<p><%= form.submit '更新' %></p>
<% end %>

docker/main/diary/app/views/articles/index.html.erb
<h1>記事一覧</h1>
<% @articles.each do |article| %>
<article>
<header>
<h2><%= link_to article.title, article_path(article) %></h2>
<p><span><%= article.user.name %></span>
<time datetime="<%= article.created_at.strftime(
  '%FT%T') %>"><%= article.created_at.strftime(
  '%Y/%m/%d %T') %></time></p>
</header>
<p><%= article.content %></p>
</article>
<% end %>

docker/main/diary/app/views/articles/new.html.erb
<h1>記事新規作成</h1>
<%= form_with model: @article do |form| %>
<p><label>タイトル<%= form.text_field :title %></label></p>
<p><label>本文<br />
<%= form.text_area :content %></label></p>
<p><%= form.submit '作成' %></p>
<% end %>

docker/main/diary/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><span><%= @article.user.name %></span>
<time datetime="<%= @article.created_at.strftime(
  '%FT%T') %>"><%= @article.created_at.strftime(
  '%Y/%m/%d %T') %></time></p>
</header>
<p><%= @article.content %></p>
<% if @current_user && @article.user_id == @current_user.id %>
<p><%= link_to '編集', edit_article_path(@article) %></p>
<%= form_with url: article_path(
  @article), method: 'DELETE' do |form| %>
<p><%= form.submit '削除' %></p>
<% end %>
<% end %>

docker/main/diary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if @current_user %>
        <p>ようこそ、<%= @current_user.name %>さん</p>
        <p><%= link_to '記事新規作成',
        controller: 'articles', action: 'new' %></p>
        <%= form_with url: url_for(
          controller: 'logout', action: 'index') do |form| %>
          <p><%= form.submit 'ログアウト' %></p>
        <% end %>
      <% else %>
        <p>ようこそ、ゲストさん <%=
        link_to 'ログイン',
        controller: 'login', action: 'index' %></p>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

docker/main/diary/app/views/login/index.html.erb
<h1>ログイン</h1>
<%= form_with url: url_for(controller: :login,
  action: :do_login) do |form| %>
  <p><label>ユーザー名<%=
  form.text_field :username %></label></p>
  <p><label>パスワード<%=
  form.password_field :password %></label></p>
  <p><%= form.submit 'ログイン' %></p>
<% end %>

docker/main/diary/app/views/top/index.html.erb
<h1>日記帳</h1>
<p>日記帳ページです</p>
<p><%= link_to '記事一覧へ', articles_path %></p>